website/models.py
from . import conn
from bson.objectid import ObjectId

db = conn.db

def create_exam(exam: dict, collection_name: str):
    """
    Inserts an exam document into the given collection

    Args:
        exam (dict): document in dictionary format to be inserted
        collection_name (str): name of the collection

    Returns:
        (int) Inserted id of the document
    """

    coll = db[collection_name]

    return coll.insert_one(exam).inserted_id

def retrieve_exam(id: str, collection_name: str):
    """
    Retrieves the document from the given collection and id

    Args:
        id (str): id of the document
        collection_name (str): collection where the document is stored

    Returns:
        (dicc) Document with the exam data
    """

    objInstance = ObjectId(id)
    coll = db[collection_name]

    return coll.find_one(objInstance)

def compare_exams(exam1: dict, exam2: dict):
    """
    Given two exams, compares their answers

    Args:
        exam1 (dict): first exam to compare
        exam2 (dict): second exam to compare

    Returns:
        (str) Number of matching answers and total questions
    """

    correct = 0
    total = 0

    for questions1, questions2 in zip(exam1['lista_preguntas'], exam2['lista_preguntas']):
        if questions1['respuesta_correcta'] == questions2['respuesta_correcta']:
            correct += 1
        total += 1

    return [correct, total]

def add_exam_data(exam: dict, departament: str, course: str, professor: str, date: str):
    """
    Add complemetary information to the exam document

    Args:
        exam (dict): document where the data will be added
        department (str): department that applied the exam
        course (str): course that applied the exam
        professor (str): professor that applied the exam
        date (str): date of the exam

    Returns:
        (str) Number of matching answers and total questions
    """

    if departament != "":
        exam['departamento'] = departament

    if course != "":
        exam['materia'] = course

    if professor != "":
        exam['profesor'] = professor
    
    if date != "":
        exam['fecha'] = date

website/__init__.py
from flask import Flask
from dotenv import load_dotenv
from flask_pymongo import PyMongo
import os
import logging

conn = PyMongo()

def create_app():
    load_dotenv()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    )
    log = logging.getLogger(__name__)

    app = Flask(__name__)
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
    app.config['MONGO_URI'] = os.getenv('MONGO_URI')
    app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024
    conn.init_app(app)

    if conn is not None:
        log.info("Successful connection to MongoDB Atlas")
    else:
        log.error("Not connected to MongoDB Atlas")

    from .views import views

    app.register_blueprint(views, url_prefix='/')

    return app

website/views.py
import shutil
import os
import logging
from docx2pdf import convert
from flask import Blueprint, request, render_template, redirect, url_for, Response
from werkzeug.utils import secure_filename
from .models import compare_exams, create_exam, retrieve_exam
from io import BytesIO
from .services_chat import get_openAI_response, modes_of_operation
from .services_format import create_document
from .models import add_exam_data
from .views_utils import get_uploaded_file, save_upload, docx_to_pdf

views = Blueprint('views', __name__)
log = logging.getLogger(__name__)

@views.route('/', methods=['GET', 'POST'])
def home():  
    """
    Loads the home page template

    Returns:
        Renders the 'home.html' template
    """ 

    return render_template('home.html')

@views.route('/procesar', methods=['POST'])
def procesar():
    """
        Takes the input file and sends it to the OpenAI to be evaluated

        POST: Processes the input file and obtains a result from the OpenAI API to be rendered in the home page

        Parameters:
            request.files['fileUpload']: file to be evaluated

        Returns:
            If POST, render home page with the result and new pdf;
            else, redirects to home page
    """

    UPLOAD_FOLDER = './fileCache'
    os.makedirs("fileCache", exist_ok=True)

    file, filename, extension = get_uploaded_file(request, "fileUpload")
    path = save_upload(file, filename, UPLOAD_FOLDER)

    if extension == ".docx":
        pdf_out = os.path.join(UPLOAD_FOLDER, os.path.splitext(filename)[0] + ".pdf")
        docx_to_pdf(path, pdf_out)
        pdf_for_model = pdf_out
    else:
        pdf_for_model = path

    departamento = request.form.get('departamento', '')
    profesor = request.form.get('profesor', '')
    materia = request.form.get('materia', '')
    fecha = request.form.get('fecha', '')
    action = request.form.get('action', '')
    exam = {}

    if action != '':
        log.info(f"Sending request with: path={pdf_for_model} & action={action}")
        result = get_openAI_response(pdf_for_model, action)
        log.info(f"Document to be stored:\n{result}")
        if isinstance(result, list):
            log.info(f"Registering exam with {len(result)} questions")
        exam['lista_preguntas'] = result
        add_exam_data(exam, departamento, materia, profesor, fecha)
        id_obj = create_exam(exam, action)
        log.info("Exam successfully processed")

    try:
        shutil.rmtree(UPLOAD_FOLDER)
        log.info("Temporary upload folder deleted successfully.")
    except Exception as e:
        log.error(f"Error deleting upload folder: {e}")

    return render_template('home.html', resultado=id_obj, action=action)

@views.route('/validar', methods=['POST'])
def validar():
    """
        Takes the input file and sends it to the OpenAI to be evaluated and then compare it with a previous results

        POST: Processes the input file and obtains a result from comparing the previous document and the current one

        Parameters:
            request.files['fileUpload']: file to be evaluated

        Returns:
            If POST, render home page with the results;
            else, redirects to home page
    """

    UPLOAD_FOLDER = './fileCache'
    os.makedirs("fileCache", exist_ok=True)

    recent_id = request.form.get('recentId', '')
    if recent_id != "Most recent document ID":
        file, filename, extension = get_uploaded_file(request, "fileUpload")
        path = save_upload(file, filename, UPLOAD_FOLDER)

        if extension == ".docx":
            pdf_out = os.path.join(UPLOAD_FOLDER, os.path.splitext(filename)[0] + ".pdf")
            docx_to_pdf(path, pdf_out)
            pdf_for_model = pdf_out
        else:
            pdf_for_model = path

        action = request.form.get('action', '')
        exam = {}

        if action != '':
            log.info(f"Sending request with: path={pdf_for_model} & action={action}")
            result = get_openAI_response(pdf_for_model, action)
            log.info(f"Document to be stored:\n{result}")
            exam['lista_preguntas'] = result
            exam[f'{action}_id'] = recent_id
            id_obj = create_exam(exam, action)

        exam1 = retrieve_exam(id_obj, action)
        action_not_used = [value for value in modes_of_operation if value != action][0]
        exam2 = retrieve_exam(recent_id, action_not_used)

        evalua = compare_exams(exam1, exam2)
        log.info("Exam successfully validated")

        try:
            shutil.rmtree(UPLOAD_FOLDER)
            log.info("Temporary upload folder deleted successfully.")
        except Exception as e:
            log.error(f"Error deleting upload folder: {e}")

        return render_template('home.html', resultado=id_obj, action=action, validar=True, evalua=evalua)
    
    return render_template('home.html')

@views.route('/generate_pdf', methods=['GET'])
def generate_pdf():
    """
        Generates a pdf of the input file with the correct answers formated

        Returns:
            The bytes from a buffer where the pdf is stored
    """

    id1 = request.args.get('id')
    action = request.args.get('action')

    dicc = retrieve_exam(id1, action)
    action_not_used = [value for value in modes_of_operation if value != action][0]

    buffer = BytesIO()
    create_document('titulo', dicc['lista_preguntas'], buffer)
    buffer.seek(0)
    response = Response(buffer.getvalue(), mimetype='application/pdf')

    validar = request.args.get('validar')
    if validar and (action_not_used in dicc):
        dicc2 = retrieve_exam(dicc[action_not_used])
        correct, total = compare_exams(dicc, dicc2)
        return response, [correct, total]

    return response

website/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mh22 Grader</title>
    <!-- Enlace al CSS de Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        html, body { height: 100%; margin: 0; }
        body { display: flex; flex-direction: column; }
        .footer { margin-top: auto; }
    </style>
    {% block extraStyle %} {% endblock %}
</head>

<body>
    <!-- Barra de navegación -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">
            <img src="../static/navbar-icon.png" width="30" height="30" class="d-inline-block align-top" alt="">
            Exam Grader
        </a>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <form class="form-inline">
                        <input class="form-control mb-2 mr-sm-2" type="search" placeholder="Usuario" aria-label="Usuario">
                        <input class="form-control mb-2 mr-sm-2" type="password" placeholder="Contraseña" aria-label="Contraseña">
                        <button class="btn btn-outline-success mb-2" type="submit">Iniciar Sesión</button>
                    </form>   
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Registrarse</a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- Contenido principal de la página -->
    <main class="flex-fill">
        {% block content %} {% endblock %}
    </main>

    <div class="container"></div>

    <!-- Pie de página -->
    <footer class="footer mt-auto py-2 bg-light">
        <div class="container">
            <span class="text-muted text-right">© Manuel Hermida 2024</span>
        </div>
    </footer>

    <!-- Opcional: enlaces a JavaScript de Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 

{% block extraStyle %} 
<style>
  .resultado {
      height: 600px; /* Altura fija */
      overflow-y: auto; /* Agrega scrollbar verticalmente si es necesario */
      background-color: #f8f9fa; /* Color de fondo (Bootstrap light) */
      border: 1px solid #dee2e6; /* Borde (Bootstrap) */
      padding: 15px; /* Espaciado interior */
  }
</style>
{% endblock %}

{% block content %}
<!-- Título de la página Home -->
<div class="container-fluid" style="background: linear-gradient(to right, #abcae8, #ffffff); padding: 10px;">
    <h1> Checa, valida y compara exámenes usando IA</h1>
</div>

<!-- Texto de introducción -->
<div class="container-fluid" style="padding: 10px;">
    <p style="font-size: 18px;"> 
        Esta herramienta te permite subir documentos <b>Word</b> o <b>PDF</b> para ser calificados (por ChatGPT) o almacenados
        para su posterior comparación. El objetivo es validar la eficiencia de la IA para la corrección automática de exámenes.
    </p>
</div>

<!-- Conjunto de pestañas-->
<div class="container-fluid">
    <ul class="nav nav-tabs justify-content-center bg-gradient-light" id="myTab" role="tablist">
        <!-- Titulos de pestañas -->
        <li class="nav-item w-50">
            <a class="nav-link active text-center" id="form1-tab" data-toggle="tab" href="#form1" role="tab" aria-controls="form1" aria-selected="true">1. Procesar documento: usar IA o almacenar respuestas</a>
        </li>
        <li class="nav-item w-50">
            <a class="nav-link text-center" id="form2-tab" data-toggle="tab" href="#form2" role="tab" aria-controls="form2" aria-selected="false">2. Validar documento</a>
        </li>
    </ul>
    <!-- Contenido de las pestañas -->
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="form1" role="tabpanel" aria-labelledby="form1-tab">
            <!-- Form para procesar -->
            <form id="documentProcessingForm" action="/procesar" method="post" enctype="multipart/form-data" class="text-center" style="background: radial-gradient(circle, #ccd2d8, #ffffff); padding: 10px;">
                <h5 style="font-weight: bold;">Procesar Examen</h5>
                <div class="form-group">
                    <input type="file" class="form-control-file" id="fileUploadChatGPT" name="fileUpload" required>
                </div>
                <small class="form-text" style="color: rgba(0, 0, 0, 0.5);">
                    Solo se aceptan archivos en formato Word y PDF.
                </small>
                <button type="submit" class="btn" name="action" value="examAI" style="background-color: #4CAF50; color: white; margin-bottom: 10px;">Calificar Automático</button>
                <button type="submit" class="btn" name="action" value="examProf" style="background-color: #347936; color: white; margin-bottom: 10px;">Registrar Respuestas</button>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="checkForm1" onchange="toggleFields('form1Fields')">
                    <label class="form-check-label" for="checkForm1">
                        Añadir datos adicionales
                    </label>
                </div>
                <div id="form1Fields" style="display: none;">
                    <div class="row">
                        <div class="col-6">
                            <input type="text" class="form-control mt-2" placeholder="Departamento" name="departamento">
                            <input type="text" class="form-control mt-2" placeholder="Profesor" name="profesor">
                        </div>
                        <div class="col-6">
                            <input type="text" class="form-control mt-2" placeholder="Materia" name="materia">
                            <input type="date" class="form-control mt-2" name="fecha">
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="tab-pane fade" id="form2" role="tabpanel" aria-labelledby="form2-tab">
            <!-- Form para almacenar respuestas -->
            <form id="documentProcessingForm2" action="/validar" method="post" enctype="multipart/form-data" class="text-center" style="background: radial-gradient(circle, #ccd2d8, #ffffff); padding: 10px;">
                <h5 style="font-weight: bold;">Validar Examen</h5>
                {% if resultado %}
                    <input type="text" class="form-control mt-2" value={{resultado}} name="recentId">
                {% else %}
                    <input type="text" class="form-control mt-2" placeholder="Most recent document ID" name="recentId">
                {% endif %}
                <br>
                <div class="form-group">
                    <input type="file" class="form-control-file" id="fileVerify" name="fileUpload" required>
                </div>
                <small class="form-text" style="color: rgba(0, 0, 0, 0.5);">
                    Solo se aceptan archivos en formato Word y PDF.
                </small>
                <button type="submit" class="btn" name="action" value="examAI" style="background-color: #4CAF50; color: white; margin-bottom: 10px;">Validar IA</button>
                <button type="submit" class="btn" name="action" value="examProf" style="background-color: #007BFF; color: white; margin-bottom: 10px">Validar Prof</button>
            </form>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="resultado" style="padding: 20px; border: 1px solid #ddd;">
            {% if resultado %}
            <iframe src="{{ url_for('views.generate_pdf', id=resultado, action=action, validar=validar) }}" style="width: 100%; height: 100%;"></iframe>
            {% else %}
            <p style="color: rgba(0, 0, 0, 0.5);">El resultado aparecerá aquí.</p>
            {% endif %}
        </div>
    </div>
    <div class="col-md-6">
        <!-- Second column content goes here -->
        {% if validar %}
        <h5 style="font-weight: bold;">Desempeño de ChatGPT: </h5>
        <p style="color: rgba(0, 0, 0, 0.5);"> {{evalua[0]}} / {{evalua[1]}} </p>
        {% else %}
        <p style="color: rgba(0, 0, 0, 0.5);">Valida tu examen.</p>
        {% endif %}
    </div>
</div>


<script>
    function toggleFields(fieldsDivId) {
        const fieldsDiv = document.getElementById(fieldsDivId);
        if (fieldsDiv.style.display === "none") {
            fieldsDiv.style.display = "block";
        } else {
            fieldsDiv.style.display = "none";
        }
    }
</script>


{% endblock %}